packages:
  - core/*
  - commands/*
  - models/*
  - utils/*

catalog:
  axios: ^1.13.5
  colors: ^1.4.0
  commander: ^14.0.3
  dotenv: ^17.2.4
  import-local: ^3.2.0
  minimist: ^1.2.8
  npmlog: ^7.0.1
  path-exists: ^5.0.0
  root-check: ^2.0.0
  semver: ^7.7.3
  url-join: ^5.0.0
