packages:
  - core/*
  - commands/*
  - models/*
  - utils/*

catalog:
  axios: 0.21.0
  colors: ^1.4.0
  dotenv: ^8.6.0
  import-local: ^3.2.0
  minimist: ^1.2.8
  npmlog: ^7.0.1
  path-exists: ^4.0.0
  root-check: ^1.0.0
  semver: ^7.7.3
  url-join: ^4.0.1
